# Site wide configuration

title: "Prompt Conf 2019"
description: "Prompt Conf 2019 - Coming Soon"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: organizers@promptconf.com
timezone: America/Chicago

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2019
  month: 9
  day: 28
  hour: 9
  minute: 0

# Site owner
owner:
  name: Prompt Conf
  email: organizers@promptconf.com
  twitter: promptconf
  facebook: promptconf
  instagram: promptconfchi
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url: http://promptconf.com
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
