# Site settings

  # These are used to personalize your new site. If you look in the HTML files,
  # you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
  # You can create any custom variable you would like, and they will be accessible
  # in the templates via {{ site.myvariable }}.

title: PromptConf 2020
email: organizers@promptconf.com
description: >- # this means to ignore newlines until "baseurl:"
  Introducing PromptConf, a polyglot tech conference coming to Chicago.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://promptconf.com" # the base hostname & protocol for your site, e.g. http://example.com
eventStartDate: 2020-09-12T10:00

registrationIsOpen: true
registrationURL: "https://ti.to/prompt-conf/2020"

twitter_username: promptconf
github_username:  promptconf
facebook_username: promptconf
instagram_username: promptconfchi

timezone: America/Chicago


# Build settings

markdown: kramdown

sass:
  sass_dir: assets/_sass

strict_front_matter: true

include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"


# Content Settings

collections:
  organizers: